// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqpzzpyieykuqakoslxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxcHp6cHlpZXlrdXFha29zbHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3NDc4MzksImV4cCI6MjA1MzMyMzgzOX0.Xf4GCjg750I8y6MoZTU3pWfQARW6XOG8DaSAkbSw2rA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);